### ISSUE TITLE
2022 布道反馈问题跟踪

### ISSUE THREAD

**Issue by JoneLau** [JoneLau/engine#7]
成都cp拜访问题跟踪
- [ ] 1. [label 默认比较模糊](https://github.com/cocos/3d-tasks/issues/13364)，需要先把字体尺寸放大再用缩放缩小才清晰 -**成都心动互娱**
- [x] 2. [压缩纹理包体变大，透明通道分离会导致有两张贴图](https://github.com/cocos/3d-tasks/issues/13365)，并且贴图间因为非 2 的次幂，贴图利用率低下。期望提高贴图利用率，在纹理没有填充满的情况下，透明通道也能合一张图上，提高图片之间的填充率。这个在低端机就比较明显（当广告出现、游戏退后台但是还在运行，这样两边同时运行的时候，内存会占用过高）-**成都心动互娱**
- [ ] 3. [多个 collider 合并到一个根节点身上](https://github.com/cocos/3d-tasks/issues/13366)。 需要 collider 组合，即使现在收集，但是没法旋转。-成都矮人科技
- [ ] 4.[ 期望在运行的时候有 try catch](https://github.com/cocos/3d-tasks/issues/13367)，资源在使用的过程中被释放了，希望不要报错，而是能定位到什么资源丢失了。其实指的是用户一旦错误释放资源，往往会引发引擎底层的一些深层报错，例如某个材质上的报错。开发者通过 bugly 等系统无法分析出具体是什么资源或者什么节点上的错误导致的，很难排查。建议是引擎能够做一些标记，在渲染报错时协助定位出具体是什么资源或者哪个渲染节点引发的错误。-**成都两英里**
- [ ] 5. [不同语言，为了让换行更自然，需要调整字号。希望语言问题，可以发起社区力量，基于规则的优化，开放规则](https://github.com/cocos/3d-tasks/issues/13369)。-**成都两英里**

**Comment by JoneLau** [comment]
自测问题
- [ ] 1. [enable transparent canvas 启用在编辑器下不生效问题](https://github.com/cocos/3d-tasks/issues/13632)
- [ ] 2. [3.6 装饰器](https://github.com/cocos/3d-tasks/issues/13672)有条件判断情况下会有警告

**Comment by JoneLau** [comment]
新功能需求
- [ ] 1. 动画面板支持[播放 spine](https://github.com/cocos/3d-tasks/issues/5645) - 大象

**Comment by JoneLau** [comment]
武汉卓讯
1. button [样式表没有继承问题](https://github.com/cocos/cocos-engine/issues/12645)
